# Generated by Django 5.2.8 on 2025-11-15 23:17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('category', models.CharField(choices=[('food', 'Їжа та напої'), ('transport', 'Транспорт'), ('shopping', 'Шопінг'), ('entertainment', 'Розваги'), ('bills', 'Комуналка/рахунки'), ('health', 'Здоровʼя'), ('other', 'Інше')], default='other', max_length=32)),
                ('ml_confidence', models.FloatField(default=0.0)),
                ('is_emotional', models.BooleanField(default=False)),
                ('emotional_tag', models.CharField(choices=[('fast_food', 'Фастфуд / імпульсивна їжа'), ('online_shopping', 'Онлайн-шопінг'), ('late_night', 'Пізні витрати'), ('entertainment', 'Розваги'), ('none', 'Не емоційна витрата')], default='none', max_length=32)),
                ('notes', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
