# Generated by Django 5.2.8 on 2025-11-15 23:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_category', models.CharField(choices=[('food', 'Їжа та напої'), ('transport', 'Транспорт'), ('shopping', 'Шопінг'), ('entertainment', 'Розваги'), ('bills', 'Комуналка/рахунки'), ('health', 'Здоровʼя'), ('other', 'Інше')], max_length=32)),
                ('corrected_category', models.CharField(choices=[('food', 'Їжа та напої'), ('transport', 'Транспорт'), ('shopping', 'Шопінг'), ('entertainment', 'Розваги'), ('bills', 'Комуналка/рахунки'), ('health', 'Здоровʼя'), ('other', 'Інше')], max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expense', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='expenses.expense')),
            ],
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(choices=[('salary', 'Зарплата'), ('freelance', 'Фріланс'), ('gift', 'Подарунки'), ('other', 'Інше')], max_length=32)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incomes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CategoryBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('food', 'Їжа та напої'), ('transport', 'Транспорт'), ('shopping', 'Шопінг'), ('entertainment', 'Розваги'), ('bills', 'Комуналка/рахунки'), ('health', 'Здоровʼя'), ('other', 'Інше')], max_length=32)),
                ('monthly_limit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'category')},
            },
        ),
    ]
